### ISSUE TITLE
[FE] 피그마 기획

### ISSUE THREAD

**Issue by Jess-Apr** [codestates-seb/seb45_pre_026#18]
### Todo
- [x] 메인페이지
- [x] 로그인 페이지
- [x] 회원가입 페이지
- [x] 마이 페이지
- [x] 질문 리스트 페이지
- [x] 개별 질문 페이지
- [x] 질문 등록 페이지
- [x] 헤더, 푸터 컴포넌트

피그마를 사용해 대략적으로 화면 구성하기
