### ISSUE TITLE
[FE] 화면 정의서 작성

### ISSUE THREAD

**Issue by Jess-Apr** [codestates-seb/seb45_pre_026#19]
### Todo
- [x] 화면 정의서 요소 채우기
- [x] 피그마에서 만든 화면 캡쳐 후 화면 미리보기로 넣기
- [x] 사용자 요구사항 정의서 요소들과 각 화면들 연결시키기
