### ISSUE TITLE
[FE]개발 환경 셋팅

### ISSUE THREAD

**Issue by Jess-Apr** [codestates-seb/seb45_pre_026#3]
### To-do
- [x] create-react-app으로 리액트 프로젝트 생성
- [x] axios 설치
- [x] react-router-dom 설치
- [x] ESLint, Prettier 설치
- [x] ESLint, Prettier 설정 파일 추가
- [x] .gitignore, LICENSE 파일 추가
